// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ApwvmC64z82RbjHGhaB3XV1WkA8nyQc',
    appId: '1:920273428105:android:b81fd900eb8cf373b3f058',
    messagingSenderId: '920273428105',
    projectId: 'metacolhub-2690c',
    storageBucket: 'metacolhub-2690c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxTowO-O5YVO-NldgQkkU6QQxJzgNJg1k',
    appId: '1:920273428105:ios:e80a83f5fc9c7ca4b3f058',
    messagingSenderId: '920273428105',
    projectId: 'metacolhub-2690c',
    storageBucket: 'metacolhub-2690c.firebasestorage.app',
    iosBundleId: 'com.example.metacolhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxTowO-O5YVO-NldgQkkU6QQxJzgNJg1k',
    appId: '1:920273428105:ios:e80a83f5fc9c7ca4b3f058',
    messagingSenderId: '920273428105',
    projectId: 'metacolhub-2690c',
    storageBucket: 'metacolhub-2690c.firebasestorage.app',
    iosBundleId: 'com.example.metacolhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_SBFIHj2pIBq6s-jBqL34CIXvcxRVTHE',
    appId: '1:920273428105:web:c77c6d27f194afb2b3f058',
    messagingSenderId: '920273428105',
    projectId: 'metacolhub-2690c',
    authDomain: 'metacolhub-2690c.firebaseapp.com',
    storageBucket: 'metacolhub-2690c.firebasestorage.app',
  );

}